// <auto-generated />
using BlazorBolos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBolos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240709023050_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorBolos.Data.Bolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Bolos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Bolo1",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_banana.jpg",
                            Nome = "Bolo1",
                            Preco = 23.45m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Bolo2",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_brigadeiro.jpg",
                            Nome = "Bolo2",
                            Preco = 21.15m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Bolo3",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_chocolate.jpg",
                            Nome = "Bolo3",
                            Preco = 43.55m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Bolo4",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_laranja.jpg",
                            Nome = "Bolo4",
                            Preco = 34.75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
